name: ServerSystem
version: 5.0
author: Tempoo50
api-version: 1.13
main: de.tempoo50.system.main.ServerSystem
depend: [Vault]

commands:
   c:
      description:
   craft:
      description:
   gm0:
      description:
   gm1:
      description:
   gm2:
      description:
   gm3:
      description:
   heal:
      description:
   SetSpawn:
      description:
   Spawn:
      description:
   v:
      description:
   fly:
      description:
   clear:
      description:
   kopf:
      description:
   kill:
      description:
   day:
      description:
   night:
      description:
   sign:
      description:
   support:
      description:
   save:
      description:
   load:
      description:
   bewerbung:
      description:
   discord:
      description:
   ts:
      description:
   web:
      description:
   yt:
      description:
   forum:
      description:
   twitter:
      description:
   shop:
      description:
   insta:
      description:
   ec:
      description:
   invsee:
      description:
   tp:
      description:
   partner:
      description:
   sethome:
      description:
   home:
      description:
   delhome:
      description:
   msg:
      description:
   r:
      description:
   start:
      description:
   cblock:
      description:
   tpa:
      description:
   tpaccept:
      description:
   tphere:
      description:
   fb:
      description:
   help:
      description:
   warp:
      description:
   setwarp:
      description:
   delwarp:
      description:
   sun:
      description:
   rain:
      description:
   gm4:
      description:
   ontime:
      description:
   live:
      description: 
   blacklist:
      description:
   belohnung:
      description:  
   seeip:
      description:
   rundruf:
      description:    
   holo:
      description:
   vote:
      description:
   rename:
      description:
   repair:
      description:
   gm5:
      description:
   fail:
      description:
   spawnmob:
      description:
   report:
      description:
   spec:
      description:
   finish:
      description:
   case:
      description:
   create:
      description:
   chest:
      description:
   premium:
      description:
   msgtoggle:
      description:
   perks:
      description:
   tiktok:
      description:
   clan:
      description:
   eco:
      description:
   pay:
      description:
   set:
      description:
   payall:
      description:
   cm:
      description:
   world:
      description: